version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # RabbitMQ Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./rabbitmq-config:/etc/rabbitmq/conf.d
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    user: "1000:1000"  # Run as non-root user
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - BROKER_URL=pyamqp://guest:guest@rabbitmq//
      - REDIS_HOST=redis
      - WEBHOOK_URL=http://api:8000/webhook/status
    volumes:
      - ./data:/data  # 입력/출력용 파일 공유
      - ./tasks:/app/tasks
        
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - BROKER_URL=pyamqp://guest:guest@rabbitmq//
      - REDIS_HOST=redis
    volumes:
      - ./tasks:/app/tasks
